import torch
import torch.nn as nn
import torch.nn.functional as F

class ARLSTMDecoder(nn.Module):
    def __init__(self, latent_dim, hidden_dim=256, num_layers=2, seq_len=50):
        super().__init__()
        self.seq_len = seq_len
        self.vocab_size = 5
        self.latent_proj = nn.Linear(latent_dim + 1, hidden_dim)
        self.lstm = nn.LSTM(input_size=self.vocab_size, hidden_size=hidden_dim, num_layers=num_layers, batch_first=True)
        self.output_proj = nn.Linear(hidden_dim, 4)

    def forward(self, latent, rl):
        batch_size = latent.size(0)
        h0 = self.latent_proj(torch.cat([latent, rl], dim=-1)).unsqueeze(0)
        h0 = h0.repeat(self.lstm.num_layers, 1, 1)
        c0 = torch.zeros_like(h0)
        
        start_token = torch.zeros((batch_size, 1, self.vocab_size), device=latent.device)
        start_token[:, 0, 4] = 1 
        input_token = start_token
        h, c = h0, c0
        
        outputs = []
        for _ in range(self.seq_len):
            out, (h, c) = self.lstm(input_token, (h, c))
            logits = self.output_proj(out.squeeze(1))
            outputs.append(logits.unsqueeze(1))
            
            # Autoregressive teacher forcing or free-running based on argmax
            next_token = F.one_hot(logits.argmax(dim=-1), num_classes=4).float()
            next_input = torch.zeros((batch_size, self.vocab_size), device=latent.device)
            next_input[:, :4] = next_token
            input_token = next_input.unsqueeze(1)
            
        return torch.cat(outputs, dim=1)

    def sample_with_log_probs(self, latent, rl):
        batch_size = latent.size(0)
        h = self.latent_proj(torch.cat([latent, rl], dim=-1)).unsqueeze(0).repeat(self.lstm.num_layers, 1, 1)
        c = torch.zeros_like(h)

        input_token = torch.zeros((batch_size, 1, 5), device=latent.device)
        input_token[:, 0, 4] = 1

        samples, log_probs = [], []
        for _ in range(self.seq_len):
            out, (h, c) = self.lstm(input_token, (h, c))
            probs = F.softmax(self.output_proj(out.squeeze(1)), dim=-1)
            dist = torch.distributions.Categorical(probs)
            sampled = dist.sample()

            samples.append(sampled.unsqueeze(1))
            log_probs.append(dist.log_prob(sampled).unsqueeze(1))

            next_input = F.one_hot(sampled, num_classes=4).float()
            input_token = torch.zeros((batch_size, 5), device=latent.device)
            input_token[:, :4] = next_input
            input_token = input_token.unsqueeze(1)

        return torch.cat(samples, dim=1), torch.cat(log_probs, dim=1)

    def evaluate_log_probs(self, latent, rl, target_tokens):
        """
        Evaluate the log probability of a given sequence of target_tokens under this model.
        target_tokens: (batch_size, seq_len) containing class indices (0-3 for ACGT).
        """
        batch_size = latent.size(0)
        h = self.latent_proj(torch.cat([latent, rl], dim=-1)).unsqueeze(0).repeat(self.lstm.num_layers, 1, 1)
        c = torch.zeros_like(h)

        input_token = torch.zeros((batch_size, 1, 5), device=latent.device)
        input_token[:, 0, 4] = 1

        log_probs = []
        for step in range(self.seq_len):
            out, (h, c) = self.lstm(input_token, (h, c))
            logits = self.output_proj(out.squeeze(1))
            step_log_probs = F.log_softmax(logits, dim=-1)
            
            # Get the actual token generated by the agent at this step
            actual_token = target_tokens[:, step].unsqueeze(1)
            
            # The log prob of the actual token
            log_prob = step_log_probs.gather(1, actual_token)
            log_probs.append(log_prob)

            # Teacher force the actual token to be the input to the next step
            next_input = F.one_hot(actual_token.squeeze(1), num_classes=4).float()
            input_token = torch.zeros((batch_size, 5), device=latent.device)
            input_token[:, :4] = next_input
            input_token = input_token.unsqueeze(1)

        return torch.cat(log_probs, dim=1)

class GATAutoEncoder(nn.Module):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder
        
    def forward(self, batch):
        latent, rl_pred = self.encoder(batch)
        decoded_logits = self.decoder(latent, rl_pred)
        return decoded_logits, rl_pred
